module.exports = Object.freeze({
  API_ON_CONNECT     : "API_ON_CONNECT",
  API_GAME_CREATE    : "API_GAME_CREATE",
  API_GAME_JOIN      : "API_GAME_JOIN",
  API_GAME_LEAVE     : "API_GAME_LEAVE",
  API_GAME_START     : "API_GAME_START",
  API_GAME_SEND_MOVE : "API_GAME_SEND_MOVE",
  API_GAME_UPDATE    : "API_GAME_UPDATE",
});